#!/bin/bash

# run the following to ensure correct executable permissions
# chmod +x .git/hooks/pre-commit

# alternately, store this file in a git-hooks/ directory, and run this to allow to execute
# git config core.hooksPath git-hooks

for file in $(git diff --cached --name-only | grep -E '\.(js|jsx)$')
do
  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run lint."
    exit 1 # exit with failure status
  fi
done